### ISSUE TITLE
Incorrect version for bind

### ISSUE THREAD

**Issue by ghost** [baulk/bucket#10]
Hi

Could you remove the "999." from the version of bind? It currently reads 
```
"version": "999.9.16.36",
```
but should be
```
"version": "9.16.36",
```
which would be the version which is downloaded.

This would also clean up the version history for [bind on repology](https://repology.org/project/bind/versions).

Thanks

**Comment by fcharlie** [comment]
Since the latest version of bind no longer supports Windows, I deliberately set its version to the wrong version `999.9.16.36`.

**Comment by fcharlie** [comment]
bind has been removed.
